apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: http
    port: 5001
    targetPort: 5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      serviceAccountName: mcp-toolbox-sa
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/kims-boutique-472014/gke-hackathon-repo/recommendation-agent:v8
        ports:
        - containerPort: 8080 # gRPC
        - containerPort: 5001 # HTTP
        env:
          - name: GOOGLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: gemini-api-key
                key: key