apiVersion: v1
kind: Service
metadata:
  name: mcp-toolbox-service
spec:
  type: ClusterIP
  selector:
    app: mcp-toolbox-server 
  ports:
  - name: http
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-toolbox-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-toolbox-server
  template:
    metadata:
      labels:
        app: mcp-toolbox-server
    spec:
      serviceAccountName: mcp-toolbox-sa 
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/kims-boutique-472014/gke-hackathon-repo/mcp-toolbox:v15
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        env:
          # This now points to the proxy sidecar, not a public IP
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_NAME
            value: "postgres"
          # These values come from the Kubernetes Secret
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: boutique-db-credentials
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: boutique-db-credentials
                key: password
      
      # Container 2: The Cloud SQL Auth Proxy Sidecar
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          - "--structured-logs"
          # Format: "project:region:instance"
          - "kims-boutique-472014:us-central1:boutique-db-instance"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi